-- Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Publishing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publishing` (
  `id_publishing` INT NOT NULL,
  `publishing` CHAR(256) NOT NULL,
  PRIMARY KEY (`id_publishing`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `id_category` INT NOT NULL,
  `category` CHAR(256) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Topic` (
  `id_topic` INT NOT NULL,
  `topic` CHAR(256) NOT NULL,
  PRIMARY KEY (`id_topic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book` (
  `book_id` INT NOT NULL,
  `book_new` CHAR(3) NULL,  
  `book_name` CHAR(256) NOT NULL,
  `book_price` INT NOT NULL,
  `book_pages` INT NOT NULL,
  `book_format` CHAR(30) NOT NULL,
  `book_date` DATE NOT NULL,
  `book_circulation` INT NOT NULL,
  `book_publishing_id` INT NULL,
  `book_category_id` INT NULL,
  `book_topic_id` INT NULL,
  PRIMARY KEY (`book_id`),
  CONSTRAINT `book_id_publishing`
    FOREIGN KEY (`book_publishing_id`)
    REFERENCES `mydb`.`Publishing` (`id_publishing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_id_category`
    FOREIGN KEY (`book_category_id`)
    REFERENCES `mydb`.`Category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_id_topic`
    FOREIGN KEY (`book_topic_id`)
    REFERENCES `mydb`.`Topic` (`id_topic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
